version: '3.7'

services:
  database:
    image: mysql:8.3.0
    container_name: mysql
    volumes:
      - development_database:/var/lib/mysql
      - ./configurations/production/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3310:3306"
volumes:
  development_database:
