# Place this at root folder of this repo

version: '3.7'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./source
    environment:
      - BASE_URL=http://example.com/  # Don't forget to change this according to your project
      - CI_ENVIRONMENT=production
      - DB_DEFAULT_HOSTNAME=database
      - DB_DEFAULT_DATABASE=main
      - DB_DEFAULT_USERNAME=root
      - DB_DEFAULT_PASSWORD=root
      - DB_DEFAULT_DBDRIVER=MySQLi
      - DB_DEFAULT_PORT=3306
      - DB_TESTS_HOSTNAME=database
      - DB_TESTS_DATABASE=test
      - DB_TESTS_USERNAME=root
      - DB_TESTS_PASSWORD=root
      - DB_TESTS_DBDRIVER=MySQLi
      - DB_TESTS_PORT=3306
    volumes:
      - source-code:/var/www
    depends_on:
      - database
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./configurations/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - source-code:/var/www
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  database:
    image: mysql:8.3.0
    container_name: mysql
    volumes:
      - production_database:/var/lib/mysql
      - ./configurations/production/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3310:3306"
volumes:
  production_database:
  source-code:
