# Place this at root folder of this repo

version: '3.7'

services:
  fpm:
    container_name: fpm
    build:
      context: ./source
    environment:
      - CI_ENVIRONMENT=production
      - database.default.hostname = db-main
      - database.default.database = main
      - database.default.username = root
      - database.default.password = root
      - database.default.DBDriver = MySQLi
      - database.default.DBPrefix =
      - database.default.port = 3310
    volumes:
      - source-code:/var/www
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./configurations/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - source-code:/var/www
    ports:
      - "8000:80"
volumes:
  source-code:
