# Place this at root folder of this repo

version: '3.7'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./source
    environment:
      - CI_ENVIRONMENT=production
      - DB_DEFAULT_HOSTNAME=db-main
      - DB_DEFAULT_DATABASE=main
      - DB_DEFAULT_USERNAME=root
      - DB_DEFAULT_PASSWORD=root
      - DB_DEFAULT_DBDRIVER=MySQLi
      - DB_DEFAULT_PORT=3306
      - DB_TESTS_HOSTNAME=db-test
      - DB_TESTS_DATABASE=test
      - DB_TESTS_USERNAME=root
      - DB_TESTS_PASSWORD=root
      - DB_TESTS_DBDRIVER=MySQLi
      - DB_TESTS_PORT=3306
    volumes:
      - source-code:/var/www
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./configurations/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - source-code:/var/www
    ports:
      - "8000:80"
  db-main:
    image: mysql
    volumes:
      - main_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
    ports:
      - "3310:3306"
  db-test:
    image: mysql
    volumes:
      - test_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3311:3306"
volumes:
  main_mysql_data:
  test_mysql_data:
  source-code:
